### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mknobi**
Added correct directory change

### CODE REVIEW

**Comment by dongahn** [comment]
This looks ok. @simoatze: do you want me to merge this? Once this is merged, I will rebase my other pull.

**Comment by simoatze** [comment]
@dong Yes thanks! and then we can merge your pull request.

**Comment by dongahn** [comment]
@simoatze: do you want me to remove README.org as part of this PR as well?

**Comment by simoatze** [comment]
Yes please! Thanks @dongahn

**Comment by dongahn** [comment]
@simoatze, I thought you wanted me to incorporate REAME.org removal into this PR... I will do a separate PR for that one. In general, it should always help to have all the relevant changes into a single commit/PR in case others need to keep track of the change history better. Just FYI for future commits/PRs.

**Comment by simoatze** [comment]
Sorry @dongahn for some reasons I thought the change was already there.

**Comment by dongahn** [comment]
Not a problem! 

BTW, there was another PR. Was that merged as well? 

We probably need to make sure one of my PRs did not override the change made from the previous PR...

My preference would be to have some committer protocol to avoid such situations. 

When the committer (@simoatze you in this case) merges a PR in, he/she let the other PR provider  to know there was a new merge so that the provider need to rebase the local branch from which the PR came from against upstream/master. 

Does it make sense?

**Comment by simoatze** [comment]
Yeah it does, but I didn't change anything because in this pull request the cmake command was in one line while I usually put every parameter in a new line with a '\' so we won't pass 80 characters.

**Comment by dongahn** [comment]
Got it! Thanks.

Please consider my above comments just as a future reference :-)

**Comment by simoatze** [comment]
@dongahn Sounds good!
I think all is good now, and Travis CI is passing the test.

**Pull request closed without merging**
