### PR TITLE
Update InstrumentParallel.cpp

### LINKED ISSUE #21: Suppression for libarcher.sa
Suppression for libomp.so and libarcher.so is made by the function  in "__tsan_default_suppressions" or through a file declared using the TSAN_OPTION. In branch manage_clock the suppression.txt has been updated but we need to update also the function redefined automatically by clang-archer at compile time. Also the suppression.txt suppress ompt_tsan.so, however the new name should be libarcher.so.

### PR DESCRIPTION
**Pull request by simoatze**
Added suppression in "__tsan_default_suppressions" function inserted by the instrumentation pass (Resolve #21).

### CODE REVIEW

**Comment by dongahn** [comment]
@simoatze: is there an issue ticket for this problem? If so, it would be good to list it here gor better tracking. If not, could yoi create a short one, thulis will help review this PR.

**Comment by simoatze** [comment]
@dongahn Joachim added the suppression in the suppression file, I was just adding the same in the function that is inserted at instrumentation time, so we don't need to specify the explicitly the suppression file with the env var TSAN_OPTION. I didn't open an issue because it was just an integration. Do you want me to open it?

**Comment by dongahn** [comment]
@simoatze: thanks. Yes, please copy and paste your comment into a new new issue and refer it in this PR. This way, if someone other than us can trace back the topic of this PR when they look at the commit message. Also, if you have "Resolve #N" in your PR message body (where N is the issue ticket number), merging your PR will automatically close that issue. Thanks.

**Comment by dongahn** [comment]
LGTM. Since this is @jprotze 's branch, i will let him review this and merge if ok.

**Pull request merged**
