### PR TITLE
Build test fix

### PR DESCRIPTION
**Pull request by lee218llnl**
When doing a standalone build, I don't think it is safe to assume that the OpenMP runtime is installed in the same directory as is specified as the Archer installation prefix. This PR adds an OMP_PREFIX macro that can be set to the prefix of the OpenMP runtime. This is used for the search of omp.h, ompt.h, and libomp.so.

Also, I noticed that `ninja check-libarcher` would fail if LD_LIBRARY_PATH is not set for archer and the openmp runtime. Since we know where these both exist, this PR sets an rpath to those libraries, thus avoiding the need to set LD_LIBRARY_PATH.

### CODE REVIEW

**Comment by simoatze** [comment]
Hi Greg, the README.md is generated from the README.org, can you put those changes in the .org? I'll regenerate the README.md once you are done. Also FYI the Travis CI tests are failing, but I'll let you finish and see if there are other problems.

**Comment by lee218llnl** [comment]
OK, I pushed the README.org changes. I'm not sure how to modify the travis setup, but I think you will need to add -D OMP_PREFIX:PATH=$OPENMP_INSTALL to Archer's cmake command.

**Comment by lee218llnl** [comment]
OK, looks like I managed to update the travis test and get it to work.

**Comment by simoatze** [comment]
@lee218llnl Thanks a lot Greg! I'll regenerate the README.md.

**Pull request merged**
