### PR TITLE
Fixed wrapper, added path to header files and libarcher library when …

### LINKED ISSUE #23: Archer wrappers don't link against libarcher.so automatically
@jprotze pointed out that we have always to manually add -larcher when linking a program compiled with Archer. It is necessary to modify the Archer wrapper to add the libarcher libarary when using the OMPT support version.

### PR DESCRIPTION
**Pull request by simoatze**
…linking (when Archer is compiled with OMPT support). This resolves #23.

### CODE REVIEW

**Comment by dongahn** [comment]
If $OMP_PREFIX/lib is where libarcher resides, this looks good to me.

**Comment by simoatze** [comment]
@dongahn $OMP_PREFIX/lib is for the OpenMP library, for archer I added @LLVM_ROOT@/lib which is the path where archer will be installed.

**Comment by dongahn** [comment]
We will also see if 'resolves #num '  will automatically close the issue upon merge!

**Comment by dongahn** [comment]
Don't we need another rpath in the case or the rpath to LLVM_ROOT is already included somewhere?

**Comment by simoatze** [comment]
I think you are right, I'll make an rpath like the one for the OpenMP lib.

**Comment by simoatze** [comment]
I committed the fix, do I have to do a new PR and close this one without merging?

**Comment by dongahn** [comment]
LGTM. What you can do is to squash the second commits to the first.

I typically do this with rebate -i SHA where SHA is the hash of the old commit.

Once you rewrite the commit history, you can force a push to the same branch where this PR came from. You may want to use this as an exercise?

**Comment by simoatze** [comment]
I think I did it! :)

**Comment by dongahn** [comment]
Cool! I will merge when ci smiles you with green :)

**Comment by dongahn** [comment]
Oh one nit. Please revise the commit message so that we can track this change better in the future.

**Comment by simoatze** [comment]
I fixed the commit message too (I am getting use to this rebase haha). Looks like the tests were successful.

**Comment by dongahn** [comment]
Yeah, rebase is one of those magic tools that can make really clean traceable commit history with no intermediate state. Merging! Thanks.

**Comment by simoatze** [comment]
@dongahn reopening, I think you didn't actually merge.

**Comment by simoatze** [comment]
I actually did a mistake, I'll fix it and rebase.

**Comment by simoatze** [comment]
I needed to add the include path for `omp.h`. Al should be good now.

**Comment by dongahn** [comment]
my bad. Thanks.

**Pull request merged**
