### PR TITLE
doc: add travis build status indicator

### PR DESCRIPTION
**Pull request by dongahn**
Add a travis-ci build status bar to our README.

### CODE REVIEW

**Comment by simoatze** [comment]
@dongahn The README.md is generated from the README.org so I can manage easily tables and stuff like that. I'll add it on the .org and regenerate the .md

**Comment by dongahn** [comment]
@simoatze: ah.. sorry I didn't now there was the org doc. How do you generate README.md? Is there a way to generate READM.md automatically when README.org is modified? 

Hmmm, it seems travis is failing for some reason for this PR...

**Comment by simoatze** [comment]
I'll look into that, if not I can just update the README.md and from now on we just keep the README.md.
The README.org is from Org Mode in Emacs, and has tag inside for code, tables etc.

Travis is failing because of the OpenMP annotations which don't cover all the tests, I think I will disable the OpenMP annotations tests fro now.

**Comment by dongahn** [comment]
BTW, if the exit code 66 ThreadSanitizer returns on detecting cause a test to fail, you can override it with TSAN_OPTIONS="exitcode=0" 

These options are documented at [here](https://github.com/google/sanitizers/wiki/ThreadSanitizerFlags).

**Comment by simoatze** [comment]
It's too complicated to ignore only some tests for a specific build, I'll just disable the test on the OpenMP annotations for now and leave only those with the OMPT Tool.

I think there is no way to export from org mode to markdown and put something before the Table of Contents, I'll just get rid of the org file and we'll start modifying the .md from now on.

**Comment by dongahn** [comment]
Sounds good to me. Thanks @simoatze, and sorry that I distracted you from your research work.

**Comment by simoatze** [comment]
@dongahn I was able to add a pre-commit and post-commit script to automatically generate the Markdown README from the .org.
The pre-commit checks if the README.org was modifie, if  exists it will generate the .md using emacs. The post-commit commits the new changes (README.md).
Everything is transparent, only prerequisite is to have emacs with org-mode installed.

To install the plugin from emacs do:

M-x  package-list-packages
Look for "org", press "i" to check it for installation and "x" to install.
Once it's installed you can try to modify the README.org and see if it generates and commit the README.md.

**Pull request merged**
