### PR TITLE
Update to 60

### PR DESCRIPTION
**Pull request by simoatze**
- Ported to LLVM 6.0
- Updated OMPT tests and testing infrastructure
- Added flag "-nosa" to disable static analysis
- Bug fixing

### CODE REVIEW

**Comment by simoatze** [comment]
@jprotze @dongahn when you guys have a minute to check this PR and merge it would be great.
I am still having some issues to make it work on mac os, I have a linking problem where a flag "-no-deduplication" is added by clang to the ld command. I have the same problem with the OpenMP runtime so I wonder if I cmake the OpenMP runtime should I pass some specific flag. @jprotze do you know anything about it?

**Comment by dongahn** [comment]
@simone, I am in transit but I will try to get to this as soon as I have some time. Thank you for the effort. This is heroic!

**Comment by simoatze** [comment]
@dongahn sounds good! I tried to push and have a good version of Archer. As soon as this is merged I'll work with Ian to integrate his new feature to remove duplicates and we will be close to a new Archer release more stable and with new features! I'll be working on sword soon as well since we are getting closer to IPDPS.

**Comment by dongahn** [comment]
@simone, I added some comments here and there. In general, this looks great. This is a lot of work and what release number are you thinking about?

**Comment by simoatze** [comment]
@dongahn thanks for looking into this. I still need to add more tests for regression of bugs that I fixed. And I still can't make it work on MacOS (maybe @jprotze can take a look), I have no idea why it does not report the races on the racy tests. I was thinking Archer 2.0 since this are all major changes and it will be dependent to Clang 6.0.

**Comment by dongahn** [comment]
Yes. I was going to suggest the same thing on the versioning!
________________________________

**Comment by simoatze** [comment]
I am merging this pull request, the tests are not passing because of a bug in the LLVM/Clang 6.0 binary. Since it's not possible to compile the trunk version on travis CI we need to wait for the next release to have Travis CI green again.

**Pull request merged**
